### ISSUE TITLE
Terminating client stream hangs background task on shutdown

### ISSUE THREAD

**Issue by v1b1** [sysid/sse-starlette#1]
**python**: 3.8.1 (windows 10)
**starlette**: 0.13.2
**client**: curl localhost:8080/streaming-endpoint

**code snippet**:
```python
@server.route('/streaming-endpoint', methods=['GET'])
async def stream_stats(req: Request):
  async def event_publisher():
    while True:
      yield dict(id=..., event=..., data=...)
      await asyncio.sleep(0.2)
  return EventSourceResponse(event_publisher())
```

**log output**:
```
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     127.0.0.1:63985 - "GET /streaming-endpoint HTTP/1.1" 200
<<< disconnect client, wait a few seconds, then ^C >>>

INFO:     Shutting down
INFO:     Waiting for background tasks to complete. (CTRL+C to force quit)
<<< hangs here until ^C >>>

INFO:     Finished server process [364]
INFO:     ASGI 'lifespan' protocol appears unsupported.
ERROR:    Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<LifespanOn.main() done, defined at ...\lib\site-packages\uvicorn\lifespan\on.py:44> wait_for=<Future cancelled>>
```

**Comment by sysid** [comment]
Thks for the info Victor. Will have a look when I've got time.

**Comment by sysid** [comment]
I can only reproduce this behavior if 'event_publisher' task is not stopped properly before application shutdown. The application is responsible of stopping all running async tasks before global shutdown, otherwise your observed behavior is to be expected. You might want to implement a signal handler for that.

**Comment by v1b1** [comment]
Do you have a recommendation on how to do so? I found that I can't determine when the client disconnects and so when to terminate the event_handler, and a background task does not seem to trigger. A side effect is that as more clients connect and disconnect from the streaming endpoint, there are many more tasks that do not get cleaned up.

**Comment by sysid** [comment]
I see your point. Need to give it some thought. There is `disconnected = await request.is_disconnected()  ` which might help at least in case a client disconnects.

**Comment by sysid** [comment]
Actually disconnecting clients can be handled properly, see snippet:
`
@app.route('/streaming-endpoint', methods=['GET'])
async def stream_stats(req: Request):
    async def event_publisher():
        i = 0
        disconnected = await req.is_disconnected()
        if disconnected:
            _log.info(f"Disconnecting client {req.client}")
        while True:
            disconnected = await req.is_disconnected()
            if disconnected:
                _log.info(f"Disconnecting client {req.client}")
                break
            # yield dict(id=..., event=..., data=...)
            i += 1
            yield dict(data=i)
            await asyncio.sleep(0.2)
        _log.info(f"Disconnected from client {req.client}")

    return EventSourceResponse(event_publisher())
`
However for connected client the problem still exists and you need somehow implement a Ctrl-C handler to stop the running tasks.
