### ISSUE TITLE
Is "cache-control: no-cache" the right default?

### ISSUE THREAD

**Issue by ahupp** [sysid/sse-starlette#104]
sse-starlette sets `cache-control: no-cache` as [a default response header](https://github.com/sysid/sse-starlette/blob/a918e8459e910f9d25e46cdf360790ea847b67ae/sse_starlette/sse.py#L206).

I was surprised to learn that this doesn't mean "do not cache", but rather that it should be cached, [but revalidated before serving a response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control):

> The no-cache response directive indicates that the response can be stored in caches, but the response must be validated with the origin server before each reuse, even when the cache is disconnected from the origin server.

I believe without including an ETag or Last-modified header in the response this won't actually allow for caching, but this does seem like a surprising default.  It's easy to imagine someone inadvertently adding a last-modified or etag and enabling caching of supposed-to-be-private data. 

[The EventSource spec requires](https://html.spec.whatwg.org/multipage/server-sent-events.html#the-eventsource-interface) "cache-control: no-store" (note: not no-cache) which also indicates the expectation is to bypass caches entirely, but if a client isn't using EventSource that won't take effect.

My questions/issues: Is this header default intentional, or was it intended to be no-store?

**Comment by sysid** [comment]
@ahupp thank you for bringing this to attention. 

You are absolutely right, it should be "no-store". Do you want to create are PR? Otherwise I will change it with next release.

**Comment by ahupp** [comment]
PR in https://github.com/sysid/sse-starlette/pull/105

**Comment by sysid** [comment]
[PR merged](https://github.com/sysid/sse-starlette/commit/db66f62d98fa14b8bdb3dce053dfeaf6fd87b7b2)
