### ISSUE TITLE
With the default sep '\r\n', some chunk send to the client is missing

### ISSUE THREAD

**Issue by xiaoxinw** [sysid/sse-starlette#108]
I'm encountering a strange issue. When using the default separator '\r\n' and sending a relatively large chunk (which is an OpenAI message, potentially with large content), the client does not receive this chunk. However, subsequent chunks are received without any problem. After changing the separator to '\n', the issue was resolved. Does anyone know the reason behind this?

**Comment by sysid** [comment]
closed due to inactivity
