### ISSUE TITLE
Support Pydantic directly

### ISSUE THREAD

**Issue by MatthewScholefield** [sysid/sse-starlette#111]
Hi there! I'd love to be able to emit Pydantic models directly like the following:

```python
...

class NumberEvent(BaseModel):
    number: int

async def numbers(minimum, maximum):
    for i in range(minimum, maximum + 1):
        await asyncio.sleep(0.9)
        yield NumberEvent(number=i)

async def sse(request):
    return EventSourceResponse(numbers(1, 5))
...
```

Right now this will just use the string representation of the model but it'd be nice for it to call `.model_dump_json()` rather than using the string representation (mostly just used to print for debug).

This could be implemented without depending on Pydantic either via `hasattr(data, 'model_dump_json')`, or via `try: from pydantic import BaseModel; except ImportError: BaseModel = None` and `if BaseModel and isinstance(data, BaseModel)`. Would either of these approaches be considered for inclusion? No worries if not since I know this is starlette focused which isn't specifically associated with Pydantic.

**Comment by sysid** [comment]
Interesting idea! Why not just calling `NumberEvent().model_dump_json()` in your generator? Am I missing sth?

**Comment by MatthewScholefield** [comment]
For simplicity of the API. You could say the same thing about everything else; why not just emit `f"data: {json.dumps(dict(val=i))}"` within the generator rather than have the library handle it?

Also, if the API doesn't handle it, it's easy to forget the call in one of your usages which would cause it to serialize via `str(data)` essentially failing silently and you would only confusingly notice when you deserialize the json on the client side.

**Comment by sysid** [comment]
I can follow your reasoning on the convenience aspect.

However, I think the domain boundary for a SSE library is to implement the protocol. Everything else should be handled by the client. After all, pydantic is just one of several object serialisation options. 

Thanks again for taking the initiative here! This is how Open Source thrives. But in this particular case I am closing the discussion as won't do.
