### ISSUE TITLE
Is there a way to stop receiving 'event: ping'?

### ISSUE THREAD

**Issue by mutal** [sysid/sse-starlette#16]
When receiving output from `sse-starlette` using `EventSourceResponse()`, my output looks something like this:

```
data: myoutput
data: myoutput

event: ping
data: 2020-12-22 15:33:27.463789

data: myoutput
data: myoutput

```

I get the `event:ping` messages every 15 seconds of streaming my output. Is there a way to disable this behaviour and stop getting those occasional 'event' messages?

**Comment by paxcodes** [comment]
It doesn't look like it. You can try however to give an extremely high ping interval using the `ping` argument. See EventSourceResponse constructor in https://github.com/sysid/sse-starlette/blob/master/sse_starlette/sse.py

**Comment by sysid** [comment]
This works as designed to prevent proxy issues on the network path.

**Comment by josnin** [comment]
just in case, anyone want to know how to change

```
async def stream(url):
    eg = event_generator(url)

    event_source = EventSourceResponse(eg)
    event_source.ping_interval = 600 #ping every 10 mins

    return event_source
```
