### ISSUE TITLE
py.typed file missing in 1.x versions

### ISSUE THREAD

**Issue by HugoJP1** [sysid/sse-starlette#36]
Hello, have attempted to bump sse-starlette in my repository to 1.1.1 (upgrading from 0.10.3), and I have got the following error:
```python
error: Skipping analyzing "sse_starlette.sse": module is installed, but missing library stubs or py.typed marker
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
error: Skipping analyzing "sse_starlette.sse": module is installed, but missing library stubs or py.typed marker
```

I tried downgrading to 1.1.0 and then 1.0.0, and they all have the same issue. Looking into the bundle as downloaded from pypi, the `py.typed` file is no longer being included.

See downloaded bundle for 0.10.3:
![image](https://user-images.githubusercontent.com/89470921/180974193-c02e47d4-7675-4855-8518-9975ccfb3370.png)

Compared to 1.1.1:
![image](https://user-images.githubusercontent.com/89470921/180974312-5eec9803-7682-48ce-8a22-5eb292f1e485.png)

I had a look at the code to see if there was anything obvious which had changed from the previous version which could cause this behaviour, and the `setup.py` and `Manifest.in` files seem correct to me. The only thing is that maybe `MANIFEST.in` should be uppercase, but I don't see how that could really cause a problem.

**Comment by sysid** [comment]
Thanks @HugoJP1 for bringing this to attention. Fixed it with version 1.1.2.

**Comment by HugoJP1** [comment]
Thanks @sysid ! I retested with 1.1.3 and I'm still getting the same issue with mypy, even though I can now see the `py.typed` file in the directory.
Did a bit of digging, and found that it was actually not appearing in the installed package in my virtual environment.

With 0.10.3
<img width="188" alt="image" src="https://user-images.githubusercontent.com/89470921/181102161-ca3b169c-7e7d-4be0-b206-e54dcb445015.png">

With 1.1.3
<img width="196" alt="image" src="https://user-images.githubusercontent.com/89470921/181102250-33d5aeae-5a87-4774-bd6f-1f08f368a207.png">

Not too sure how it was working before, but looking at PEP 561 (https://peps.python.org/pep-0561/)

> Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing. This marker applies recursively: if a top-level package includes it, all its sub-packages MUST support type checking as well. To have this file installed with the package, maintainers can use existing packaging options such as package_data in distutils, shown below.


> Distutils option example:
> ```
> setup(
>     ...,
>     package_data = {
>         'foopkg': ['py.typed'],
>     },
>     ...,
>     )
> ```

So I think that [setup.py](https://github.com/sysid/sse-starlette/blob/master/setup.py) needs to be updated too, similarly to how starlette is set up (https://github.com/encode/starlette/blob/master/setup.py#L37), potentially both with `package_data` and `include_package_data`.

**Comment by sysid** [comment]
This is annoying. I have no idea why the file does not get installed. 

It is included in both packages in https://pypi.org/project/sse-starlette/#files,  but does not get installed. Any ideas are welcome.

**Comment by HugoJP1** [comment]
I will let you know if I get any ideas.

**Comment by HugoJP1** [comment]
It looks like you have solved it, because this is now working again in 1.1.4:
![image](https://user-images.githubusercontent.com/89470921/181205907-8c6d98a7-73d6-435c-b8ad-151fd2119dfd.png)

Thanks!!
