### ISSUE TITLE
Various test issues/ideas

### ISSUE THREAD

**Issue by jakkdl** [sysid/sse-starlette#46]
Since you asked so nicely for ideas, I'll let you have a braindump of opinions :innocent: 

How to actually check for the race condition, which is maybe the most important part, I unfortunately have no clue how to do :sweat_smile: 

But anyway, these are all/most of the issues I encountered when writing my PR. Some is subjective / not necessary, most is due to new releases of stuff breaking other stuff. I can give you program versions if there's stuff that you can't reproduce on your end - I'm running Arch Linux with pretty up to date stuff, although ofc mostly it's just a fresh virtualenv with `pip install -r requirements.txt`
As background I've contributed to several python FOSS repos last few months, so have gotten a decent grasp on how most well-maintained foss repos do things.

## uvicorn
As far as I can see there's no documentation that you have to open 127.0.0.1:8000 in a web browser to initiate the uvicorn tests/examples. Would be nice to have that in a comment in the file and in the readme. But feels like it should be possible to automate at least a bunch of them from within python (or sh/the makefile) by making a simple web request?

## Makefile
There's quite a bit of overlap between make and tox, esp as tox only has a single environment which reformats and runs tests with coverage. I'd personally maybe just put all the test/checks in tox [in different environments], including type checking and linting. Or even better use pre-commit for checks. I haven't seen ~any projects use makefiles, but I kinda dig it tbh!

Several of the packages needed in targets are not in `requirements.txt` (mypy, flake8, any flake8 plugins) - if going the makefile route I'd maybe add target[s] for installing/upgrading packages - and/or rename `requirements.txt` to `test_requirements.txt`.

Python packaging *is* kind of a mess atm but having all of `Pipfile`, `requirements.txt`, `setup.cfg`, `setup.py`, and `pyproject.toml` - and a `Makefile`, and many also put configs in `tox.ini` - is a bit confusing x)

### `make coverage`
```
/home/h/Git/sse-starlette/.venv/lib/python3.10/site-packages/coverage/control.py:836: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
python -m coverage report -m
No data to report.
```
I recently had similar issues - I'd recommend checking out https://github.com/pytest-dev/pytest-cov/issues/98

### `make test`
```
home/h/Git/sse-starlette/.venv/lib/python3.10/site-packages/coverage/inorout.py:507: CoverageWarning: Module /sse_starlette was never imported. (module-not-imported)
  self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
/home/h/Git/sse-starlette/.venv/lib/python3.10/site-packages/coverage/control.py:836: CoverageWarning: No data was collected. (no-data-collected)
  self._warn("No data was collected.", slug="no-data-collected")
WARNING: Failed to generate report: No data to report.

/home/h/Git/sse-starlette/.venv/lib/python3.10/site-packages/pytest_cov/plugin.py:311: CovReportWarning: Failed to generate report: No data to report.

  warnings.warn(CovReportWarning(message))
```
see above
### `make tox`
works perfectly fine for me, except for missing 12-13% of coverage and it doesn't have environments for python 3.11. And ofc it'd be great if there was an environment for testing uvicorn as well.

### `make style` / `make black`
```
black /sse_starlette tests
Usage: black [OPTIONS] SRC ...
Try 'black -h' for help.

Error: Invalid value for 'SRC ...': Path '/sse_starlette' does not exist.
make: *** [Makefile:74: format] Error 2
```
### `make isort`
works perfectly fine
### `make lint`
```
ValueError: Error code ';' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
make: *** [Makefile:85: flake8] Error 1
```
### `make mypy`
```
# keep config in setup.cfg for integration with PyCharm
mypy --config-file setup.cfg /sse_starlette
mypy: can't read file '/sse_starlette': No such file or directory
make: *** [Makefile:90: mypy] Error 2
```
same error as black

## black
```
reformatted /home/h/Git/sse-starlette/examples/stream_generator.py
reformatted /home/h/Git/sse-starlette/sse_starlette/sse.py
```
## mypy
```
sse_starlette/sse.py:34: error: Cannot assign to a method  [assignment]
tests/conditional_yielding_endpoint.py:17: error: Need type annotation for "items" (hint: "items: Dict[<type>, <type>] = ...")  [var-annotated]
Found 2 errors in 2 files (checked 11 source files)
```

Cheers~

**Comment by sysid** [comment]
@jakkdl , thanks again for your suggestions. I tried to act on most of them. Testing the uvicorn related integration tests is still a manual process, though. Just do not find the time to delve into that.
Important also to note (which probably caused some of your pain): the requirements.txt was not really up to date since I am only working with Pipenv. Removed it in next release.

**Comment by jakkdl** [comment]
Awesome, happy it was of help! :rocket: :rocket:
