### ISSUE TITLE
Postman SSE Support does not work

### ISSUE THREAD

**Issue by hburrichter** [sysid/sse-starlette#47]
First of all, thank you for the great repository!

Postman [recently gained support for SSE](https://blog.postman.com/support-for-server-sent-events/) and it works as expected for some SSE endpoints I found online.

However, I tried to implement a Server-Sent Events endpoint using FastAPI/Starlette with the built-in [Starlette StreamingResponse](https://www.starlette.io/responses/#streamingresponse) and your [SSE-Startlette GitHub repo](https://github.com/sysid/sse-starlette) and neither of them produced the new streaming UI in Postman.

Any Idea on what might be the cause?

(tested it with your "usage" code from the repo readme)

**Comment by hburrichter** [comment]
Related to this issue:
https://github.com/postmanlabs/postman-app-support/issues/11753

Setting the header manually to:
```python
return EventSourceResponse(
            content=...,
            headers={
                'content-type': 'text/event-stream',
            }
        )
```
fixes the issue.

**Comment by sysid** [comment]
Thanks @hburrichter for this insight. I probably should update the README accordingly.
