### ISSUE TITLE
Response does not stream to browser from localhost (Chrome or Firefox)

### ISSUE THREAD

**Issue by bowmanjd** [sysid/sse-starlette#5]
I have used the exact example from the README. While it works fine from curl (each event shows .9 seconds apart), in the browser (Chrome or Firefox on Windows), it waits ~5 seconds, then shows the entire body once it has closed.

Have you seen this behavior? Is it an ASGI issue, or something with browsers? I have similar issues with many Python ASGI and SSE implementations. I hope I am just missing something obvious.

**Comment by paxcodes** [comment]
I didn't experience this issue when I was [trying it out](https://github.com/paxcodes/python_sse) myself. 

It sounds like an issue in the client code if it works fine from curl. Can you try using the code in [example.py](https://github.com/sysid/sse-starlette/blob/master/example.py) and see if that works?

**Comment by bowmanjd** [comment]
The `example.py` also has the same problem. No content is received until the connection is closed.

I did try a different computer, though, and that works fine. Perhaps this is a Windows issue, or particular to my machine? Firefox, Chrome, and Edge all have the same issue.

**Comment by bowmanjd** [comment]
Closing as it is clearly browser- or OS-related

**Comment by paxcodes** [comment]
SSE is expected to not work in older browsers. There are other known issues as well (see "Known Issues" tab in [caniuse.com](https://caniuse.com/#feat=eventsource)). Other than those, I can't think of anything else.

**Comment by bowmanjd** [comment]
Good point about the older browsers; however, I am using the latest versions of Chrome, Edge, and Firefox.

It turns out it had to do with Sophos Endpoint Security's "web protection" which was intentionally forcing buffering of the first two megabytes of an event stream. Troubling.

You can find my entire write up [on StackOverflow](https://stackoverflow.com/questions/62129788/on-a-machine-running-sophos-why-do-all-my-browsers-fail-to-receive-server-sent).

I remain perplexed as to why non-Python implementations were working fine, and why ASGI does not expose and document some sort of flush method.
