### ISSUE TITLE
Authentication issue when using sysid/sse-starlette

### ISSUE THREAD

**Issue by srbdev** [sysid/sse-starlette#54]
I'm developing an API using Starlette and I've implemented authentication following their example (see https://www.starlette.io/authentication/). I've also added `sysid/sse-starlette` to the project and adding `@requires("authenticated")` to my streaming API endpoint always returns a `403 Forbidden` return code. No issues with the other `GET` or `POST` endpoints. Also note that the authentication logic succeeds at validating my credentials when hitting the streaming endpoint but somehow fails when returning the `AuthCredentials` for the user.

Unfortunately, I cannot post my code here but I was wondering if you had any idea of what could be happening. If not, I'll put together a simple and shareable example to hopefully replicate the issue and we can go from there.

Thank you!

**Comment by sysid** [comment]
I am afraid that just based on your description the problem is too vague to contribute meaningful.

**Comment by srbdev** [comment]
I figured! I'm working on an isolated example to be able to reproduce the issue.

**Comment by sysid** [comment]
Will close for now due to inactivity.
