### ISSUE TITLE
returning a stream event without "data:"

### ISSUE THREAD

**Issue by syberkitten** [sysid/sse-starlette#63]
Hi

It seems like the "data:" prefix is always returned when a stream text fragment is returned to client.

In most cases this can be fixed on the client but it would be better to be able to specify if you really need
this prefix or just return that raw data as it is.

code is in sse.py:

        if self.data is not None:
            for chunk in self.LINE_SEP_EXPR.split(str(self.data)):
                buffer.write(f"data: {chunk}")
                buffer.write(self._sep)

I can do a PR/MR if makes it easier,
simplest is to add to the yield that is going to the ServerSentEvent:

for example:
yield dict(data={
                    "text": "my text",
                }, data_prefix="")

**Comment by syberkitten** [comment]
class ServerSentEvent:
    def __init__(
        self,
        data: Optional[Any] = None,
        *,
        event: Optional[str] = None,
        id: Optional[int] = None,
        retry: Optional[int] = None,
        comment: Optional[str] = None,
        sep: Optional[str] = None,
        data_prefix="data: ",
    )
    
    
            if self.data is not None:
              for chunk in self.LINE_SEP_EXPR.split(str(self.data)):
                  buffer.write(f"{self.data_prefix}{chunk}")
                  buffer.write(self._sep)

**Comment by paxcodes** [comment]
Correct me if I'm wrong but it seems from the reading of the SSE spec (https://html.spec.whatwg.org/multipage/server-sent-events.html#the-eventsource-interface), the "data: " prefix is required if you want to send data to be processed by clients. Otherwise, the line will/should be ignored by clients following the spec.   


18 Jun 2023, 02:21 by ***@***.***:

**Comment by sysid** [comment]
My understanding concurs with @paxcodes . Please correct my understanding by pointing to the respective spec or an authoritative example.

**Comment by syberkitten** [comment]
hi @sysid and @paxcodes thanks for pointing my attention to this, closing the merge request.
