### ISSUE TITLE
Sep param does not have any effect on produced data

### ISSUE THREAD

**Issue by yunusyuksel** [sysid/sse-starlette#65]
Setting sep param does not have any effect. Since it is set through EventSourceResponse, but not passed to ServerSentevent on initialization

**Comment by sysid** [comment]
I apologise @yunusyuksel  for the late response and thank you for your feedback! This needs some investigation. I will look into it.

**Comment by sysid** [comment]
Fixed with: https://github.com/sysid/sse-starlette/releases/tag/v1.6.5
