### ISSUE TITLE
Question: How to handle client disconnection?

### ISSUE THREAD

**Issue by firatkucuk** [sysid/sse-starlette#7]
The client can unexpectedly disconnect but I couldn't find an easy way of doing that.

**Comment by paxcodes** [comment]
I have the same question. 

I already am checking  `request.is_disconnected()` but notice when client connection is "lost", it still sends PING events (see `backend_1  | TRACE:    172.24.0.3:39602 - Connection lost` that happens just before the last 2 pings:

<details>
<summary>uvicorn trace logs</summary>

```
backend_1  | INFO:     172.24.0.3:39602 - "GET /lobby/PAXY6 HTTP/1.1" 200 OK
backend_1  | DEBUG:    chunk: data: Pax
backend_1  | 
backend_1  | 
backend_1  | TRACE:    172.24.0.3:39602 - ASGI [3] Send {'type': 'http.response.body', 'body': '<13 bytes>', 'more_body': True}
backend_1  | TRACE:    172.24.0.3:39602 - ASGI [3] Receive {'type': 'http.request', 'body': '<0 bytes>', 'more_body': False}
backend_1  | DEBUG:    ping: event: ping
backend_1  | data: 2020-10-06 00:42:29.957986
backend_1  | 
backend_1  | 
backend_1  | TRACE:    172.24.0.3:39602 - ASGI [3] Send {'type': 'http.response.body', 'body': '<49 bytes>', 'more_body': True}
backend_1  | DEBUG:    ping: event: ping
backend_1  | data: 2020-10-06 00:42:44.959141
backend_1  | 
backend_1  | 
backend_1  | TRACE:    172.24.0.3:39602 - ASGI [3] Send {'type': 'http.response.body', 'body': '<49 bytes>', 'more_body': True}
backend_1  | TRACE:    172.24.0.3:39602 - Connection lost
backend_1  | DEBUG:    ping: event: ping
backend_1  | data: 2020-10-06 00:42:59.938124
backend_1  | 
backend_1  | 
backend_1  | TRACE:    172.24.0.3:39602 - ASGI [3] Send {'type': 'http.response.body', 'body': '<49 bytes>', 'more_body': True}
backend_1  | DEBUG:    ping: event: ping
backend_1  | data: 2020-10-06 00:43:14.938602
backend_1  | 
backend_1  | 
backend_1  | TRACE:    172.24.0.3:39602 - ASGI [3] Send {'type': 'http.response.body', 'body': '<49 bytes>', 'more_body': True}
```
</summary>

I wonder if these issues are at all relevant:

https://github.com/encode/uvicorn/issues/388
Discussion starting in this [comment](https://github.com/encode/starlette/issues/20#issuecomment-586304354)

**Comment by paxcodes** [comment]
The more I read this [discussion](https://github.com/encode/starlette/issues/20#issuecomment-587029936) and comparing it to the [current code](https://github.com/sysid/sse-starlette/blob/master/sse_starlette/sse.py#L135) --- the more I think this is a bug? 

What do you think @sysid ?

**Comment by sysid** [comment]
Thanks @paxcodes for your analysis, much appreciated. I tend to agree but I currently I cannot dig deeper into it. If you have an idea for a quick fix, please let me know. 

I will try to find time asap, though.

**Comment by paxcodes** [comment]
Exactly. I was looking at that.

Is there a reason why we are not simply inheriting from `StreamingResponse` similar to what this person [did](https://github.com/encode/starlette/issues/20#issuecomment-586304354)? IIUC, if we inherit StreamingResponse, this scenario will be taken care of.

**Comment by sysid** [comment]
Done. Pretty much followed your proposition. Thanks again! #10

**Comment by paxcodes** [comment]
Thanks so much, @sysid for responding so quickly. Any chance you'll publish a release soon?

**Comment by paxcodes** [comment]
By the way, I realized yesterday that checking the `/endless` endpoint works perfectly even _before_ [this PR](https://github.com/sysid/sse-starlette/pull/10) was merged.

I was simply not using request.is_disconnected() properly:

```python
async streamMessages():
        while True:
            disconnected = await req.is_disconnected()
            if disconnected:
                break
            async with broadcast.subscribe(channel=room.code) as subscriber:
                async for event in subscriber:
                    msg = event.message
                    yield msg

return EventSourceResponse(streamMessages())
```

But the merge was still beneficial since I can now do this without having to worry about client disconnection (since this package takes care of it already):

```python
async streamMessages():
    async with broadcast.subscribe(channel=room.code) as subscriber:
        async for event in subscriber:
            msg = event.message
            yield msg

return EventSourceResponse(streamMessages())
```

**Comment by vaibhavmule** [comment]
@paxcodes if you don't mind, can you share code `broadcast`, I am trying to send a notification when user creates or updates comments. the code you mentioned above looks good.

**Comment by UrbanSwati** [comment]
> @paxcodes if you don't mind, can you share code `broadcast`, I am trying to send a notification when user creates or updates comments. the code you mentioned above looks good.

I'm assuming @paxcodes is using redis or similar package

https://redislabs.com/ebook/part-2-core-concepts/chapter-3-commands-in-redis/3-6-publishsubscribe/

**Comment by paxcodes** [comment]
Thanks for chiming in @UrbanSwati -- I emailed vaibhavmule as I don't want to hi-jack this issue's thread.

**Comment by sergpsu** [comment]
Hi guys. Need a proper way to make some cleanups after client disconnects. What I've implemented looks like this:
```
class MyEventSourceResponse(EventSourceResponse):
    user_id: uuid.UUID

    def __init__(self, user_id: uuid.UUID, *args, **kwargs):
        self.user_id = user_id
        super().__init__(*args, **kwargs)

    # @staticmethod
    async def listen_for_disconnect(self, receive: Receive) -> None:
        while True:
            message = await receive()
            if message["type"] == "http.disconnect":
                #DOING CLEANUP BASED ON self.user_id
                break

```
So listen_for_disconnect cannot be staticmethod and this is not the clean way to subclass. Is there a better way?
