### ISSUE TITLE
Python type hints

### ISSUE THREAD

**Issue by lukecivantos** [sysid/sse-starlette#86]
Hey there! 

I was wondering if there were any plans to add types or type stubs to this library. 

Thanks!

**Comment by ahmedabdou14** [comment]
I was going to raise the same request here actually. It is going to be super helpful to maybe make `EventSourceResponse` accept a generic type that specifies the type of content stream sent. I am not sure if this would be of any help to `openapi` docs, but it would be nice to see the data type sent via sse within `redo` and `openapi`.

**Comment by sysid** [comment]
@ahmedabdou14 thanks for adding to the topic. I am very open for these ideas. PRs are welcome!

**Comment by ahmedabdou14** [comment]
Perfect then ;)
A PR might come very late though, i am super busy this month
You can go ahead and assign me to this issue

**Comment by sysid** [comment]
@ahmedabdou14 , closing this for now, but PR is welcome any time. Hope this is ok.
