### ISSUE TITLE
Escaping Newlines

### ISSUE THREAD

**Issue by CiberNin** [sysid/sse-starlette#96]
I'm trying to use sse-starlette with datastar, which expects server sent events with fragments like`fragment <div id='test'>\nUpdated\n</div>`
However it looks like starlette-sse always splits the data into multiple data lines when it encounters a newline.
`if self.data is not None:
            for chunk in self.LINE_SEP_EXPR.split(str(self.data)):
                buffer.write(f"data: {chunk}")
                buffer.write(self._sep)`
Unless my generator outputs bytes directly.

Is there any way to escape my newlines?

**Comment by sysid** [comment]
sse-starlette tries to implement the SSE standard. If there is a bug or misinterpretation, please let me know.
